<a href="https://colab.research.google.com/github/shlok-dhital/6CS012-AI-and-Machine-Learning/blob/main/ShlokDhital_2407091_Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **4.1 Exercise on Functions**


In [ ]:
# Task 1

def m_to_ft(meters: float) -> float:
  return meters * 3.2808

def ft_to_m(feet: float) -> float:
  return feet / 3.2808

def kg_to_lbs(kilograms: float) -> float:
  return kilograms * 2.2046

def lbs_to_kgs(pounds: float) -> float:
  return pounds / 2.2046

def l_to_gal(litres: float) -> float:
  return litres / 3.7854

def gal_to_l(gallons: float) -> float:
  return gallons * 3.7854

def get_int_input(prompt: str, min:int, max:int) -> int:
  choice = None;
  while True:
    try:
      choice = int(input(prompt))
      if (choice >= min and choice <= max):
        break;
      else:
        print(f"Enter value between {min} and {max}")
    except ValueError:
      print(f"Enter an integer value\n")
  return choice

def get_float_input(prompt: str, min:float = -float('inf'), max:float = float('inf')) -> float:
  choice = None;
  while True:
    try:
      choice = float(input(prompt))
      if (choice >= min and choice <= max):
        break;
      else:
        print(f"Enter value between {min} and {max}")
    except ValueError:
      print(f"Enter a number\n")
  return choice

def main():
  print("Convert between:")
  operations = [
    {
        "name": "Length",
        "options": [
            {"name": "Meters to Feet", "func": m_to_ft},
            {"name": "Feet to Meters", "func": ft_to_m},
        ],
    },
    {
        "name": "Weight",
        "options": [
            {"name": "Kilograms to Pounds", "func": kg_to_lbs},
            {"name": "Pounds to Kilograms", "func": lbs_to_kgs},
        ],
    },
    {
        "name": "Volume",
        "options": [
            {"name": "Litres to Gallons", "func": l_to_gal},
            {"name": "Gallons to Litres", "func": gal_to_l},
        ],
    },
  ]

  # Get operations type eg length, weight
  for i, op in enumerate(operations, start=1):
    print(f"{i}. {op["name"]}")
  print()
  type_choice = get_int_input("Enter conversion type (eg. 1): ", 1, len(operations))
  print()

  # Get conversion type
  options=operations[type_choice - 1]["options"]
  for i, opt in enumerate(options, start=1):
    print(f"{i}. {opt["name"]}")
  print()
  option_choice = get_int_input("Enter conversion option (eg. 1): ", 1, len(options))
  print()

  selected_option = options[option_choice - 1]

  # Get value to be converted
  value = get_float_input("Enter value to be converted: ", 0)
  print()

  # Print results
  print(f"{value} {selected_option["name"]} : {selected_option["func"](value):.4f}")

main()

Main Menu:
1. Length
2. Weight
3. Volume

Enter conversion type (eg. 1): 4
Enter value between 1 and 3
Enter conversion type (eg. 1): 2

1. Kilograms to Pounds
2. Pounds to Kilograms

Enter conversion option (eg. 1): -12
Enter value between 1 and 2
Enter conversion option (eg. 1): 2

Enter value to be converted: lol
Enter a number

Enter value to be converted: -12.2
Enter value between 0 and inf
Enter value to be converted: 12

12.0 Pounds to Kilograms : 5.4432


In [ ]:
# Task 2
def sum_list(nums: list) -> float:
  sum = 0
  for num in nums:
    sum += num
  return sum

def avg_list(nums: list) -> float:
  return sum_list(nums) / len(nums)

def maximum(nums: list) -> float:
  max = -float('inf')
  for num in nums:
    if num > max:
      max = num
  return max

def minimum(nums: list) -> float:
  min = float('inf')
  for num in nums:
    if num < min:
      min = num
  return min

def get_nums_input() -> list:
  nums = None
  while True:
    nums_string = input("Enter numbers separated by space (eg. 1 -2 3.2): ")
    nums = nums_string.split()
    try:
      if (len(nums) < 1):
        print("Atleast 1 number required")
        continue;
      for i in range(len(nums)):
        nums[i] = float(nums[i])
      break
    except ValueError as e:
      print("Invalid input, make sure all values are numerical")
  return nums

def get_int_input(prompt: str, min:int, max:int) -> int:
  choice = None;
  while True:
    try:
      choice = int(input(prompt))
      if (choice >= min and choice <= max):
        break;
      else:
        print(f"Enter value between {min} and {max}")
    except ValueError:
      print(f"Enter an integer value\n")
  return choice


def main():
  operations = [
      {"name": "Sum", "func": sum_list},
      {"name": "Average", "func": avg_list},
      {"name": "Maximum", "func": maximum},
      {"name": "Minimum", "func": minimum}
  ]

  for i, op in enumerate(operations, start=1):
    print(f"{i}. {op["name"]}")
  print()
  type_choice = get_int_input("Enter operation (eg. 1): ", 1, len(operations))
  print()
  selected_operation = operations[type_choice - 1]
  numbers = get_nums_input()
  print(f"{selected_operation['name']}: {selected_operation['func'](numbers)}")

main()


1. Sum
2. Average
3. Maximum
4. Minimum

Enter operation (eg. 1): 2

Enter numbers separated by space (eg. 1 -2 3.2): 10 20 30 40
Average: 25.0


# **4.2 Exercise on List Manipulation**


In [ ]:
# Extract Every Other Element

def extract_every_other(lst: list) -> list:
  return lst[::2]

print(extract_every_other([1,2,3,4,5,6,7,8,9,10]))

[1, 3, 5, 7, 9]


In [ ]:
# Slice a sublist

def get_sublist(lst: list, start: int, end: int) -> list:
  return lst[start : end + 1]

get_sublist([1,2,3,4,5,6], 0, 4)

[1, 2, 3, 4, 5]

In [ ]:
# Reverse a List Using Slicing

def reverse_list(lst):
  return lst[::-1]

reverse_list([1,2,3,4,5,6])

[6, 5, 4, 3, 2, 1]

In [ ]:
# Remove the First and Last Elements

def remove_first_last(lst: list) -> list:
  return lst[1:-1]

remove_first_last([1,2,3,4,5,6])


[2, 3, 4, 5]

In [ ]:
# Get the First n Elements

def get_first_n(lst: list, n: int) -> list:
  return lst[:n]

get_first_n([1,2,3,4,5,6], 4)

[1, 2, 3, 4]

In [ ]:
# Extract Elements from the End

def get_last_n(lst: list, n: int) -> list:
  return lst[-n:]

get_last_n([1,2,3,4,5,6], 3)

[4, 5, 6]

In [ ]:
# Extract Elements in Reverse Order

def reverse_skip(lst: list) -> list:
  return lst[-2::-2]

reverse_skip([1,2,3,4,5,6,7,8])

[7, 5, 3, 1]

# **4.3 Exercise on Nested List**

In [ ]:
# Flatten a Nested list

def flatten(lst: list) -> list:
  new_lst = []
  for item in lst:
    if (isinstance(item, list)):
      new_lst.extend(flatten(item))
    else:
      new_lst.append(item)
  return new_lst

print(flatten([[1,2], [3,4], [5, [6,7,[8]]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# Accessing Nested List Elements

def access_nested_element(lst: list, indices: list):
  accessed_value = lst;
  for i in indices:
    accessed_value = accessed_value[i]
  return accessed_value

lst = [[1,2],[3,[4,5]],6]
print(access_nested_element(lst, [1,1,0]))
# print(lst[1][1][0])


4


In [ ]:
# Sum of All Elements in a Nested List

def sum_nested(lst: list):
  sum = 0
  for item in lst:
    if (isinstance(item, list)):
      sum += sum_nested(item)
    else:
      sum += item
  return sum

lst = [[1,2],[3,[4,5]],6]
sum_nested(lst)

21

In [ ]:
# Remove Specific Element from a Nested List

def remove_elem(lst:list, elem):
  for item in lst:
    if (isinstance(item, list)):
      remove_elem(item, elem)
  try:
    return lst.remove(elem)
  except ValueError:
    return lst

lst = [[1,2], [3,2], [4,5, [8,3]]]

remove_elem(lst, 4)

[[1, 2], [3, 2], [5, [8, 3]]]

In [ ]:
# Find the Maximum Element in a Nested List

def find_max(lst: list):
  max = -float('inf')
  for item in lst:
    if (isinstance(item, list)):
      local_max = find_max(item)
    else:
      local_max = item

    if (max < local_max):
        max = local_max
  return max

lst = [[-1,-2], [-3,-2], [-4,15, [8,-3]],-1]

find_max(lst)


15

In [ ]:
# Count occurrences of an Element in a Nested List

def count_occurrences(lst: list, elem):
  count = 0;
  for item in lst:
    if (isinstance(item, list)):
      count += count_occurrences(item, elem)
    else:
     if item == elem: count += 1
  return count

lst = [[1,2], [3,2], [4,5, [8,3,[3,3,3,[3,3]]]]]
count_occurrences(lst, 3)

7

In [ ]:
# FLatten a List of Lists of Lists:

def flatten(lst: list) -> list:
  new_lst = []
  for item in lst:
    if (isinstance(item, list)):
      new_lst.extend(flatten(item))
    else:
      new_lst.append(item)
  return new_lst

print(flatten([[1,2], [3,4], [5, [6,7,[8]]]]))

In [ ]:
# Nested List Average

def average_nested(lst: list):
  flattened = flatten(lst)
  return sum(flattened) / len(flattened)


print(average_nested([[1,2], [3,4], [5, [6,7,[8]]]]))

4.5


#**10.1 Basic Vector and Matrix Operation with Numpy**

In [2]:
# imports
import numpy as np
import time

## Problem - 1: Array Creation

In [ ]:
# Initialize an empty array with size 2X2.
arr = np.empty((2,2))
print(arr)

[[3.7388734e-315 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]


In [ ]:
# Initialize an all one array with size 4X2.
arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Return a new array of given shape and type, filled with fill value.{Hint: np.full}
arr = np.full((1,16), fill_value=12, dtype=float)
print(arr)

[[12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]]


In [ ]:
# Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
arr = np.array([[2,3],[4,5]])
print(arr)
print()
arr_zeros = np.zeros_like(arr)
print(arr_zeros)

[[2 3]
 [4 5]]

[[0 0]
 [0 0]]


In [ ]:
# Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
arr = np.array([[2,3],[4,5],[6,7],[8,9]])
print(arr)
print()
arr_ones = np.ones_like(arr)
print(arr_ones)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
# For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [[1,2],[3,4]]
print(new_list)
print()
a = np.array(new_list)
print(a)

[[1, 2], [3, 4]]

[[1 2]
 [3 4]]


## Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# Create an array with values ranging from 10 to 49.

arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Create a 3X3 matrix with values ranging from 0 to 8.
# {Hint:look for np.reshape()}

arr =np.reshape(np.arange(0,9),(3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Create a 3X3 identity matrix.{Hint:np.eye()}
arr_i = np.eye(3)
print(arr_i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}

arr_rand = np.random.random(30)
print(arr_rand)
print()
print(f"Mean: {arr_rand.mean()}")

[0.35313687 0.46284182 0.0214925  0.50432587 0.73984324 0.23650427
 0.63382124 0.18422286 0.67730964 0.83092396 0.17766251 0.17135882
 0.61976345 0.5811199  0.9242799  0.92593119 0.75429165 0.70243898
 0.23284348 0.95478316 0.42858574 0.24046029 0.01136933 0.9275332
 0.90400093 0.74208806 0.41625075 0.44271377 0.32163726 0.50299663]

Mean: 0.5208843753194066


In [ ]:
# Create a 10X10 array with random values and find the minimum and maximum values.

arr_rand = np.random.random((10,10))
print(arr_rand)
print()
print(f"Max: {arr_rand.max()}")
print(f"Min: {arr_rand.min()}")

[[0.62484415 0.95430949 0.71683556 0.95062414 0.61725969 0.54252865
  0.3628051  0.74038718 0.26288538 0.79500272]
 [0.04337664 0.23093507 0.34908541 0.56012343 0.55211703 0.94188631
  0.05566518 0.07054303 0.37056405 0.20036533]
 [0.46399594 0.63779013 0.63152801 0.24287644 0.90184986 0.98393274
  0.23615606 0.75881877 0.68832965 0.10251415]
 [0.78702241 0.87243104 0.45964394 0.48255019 0.79979779 0.8175259
  0.41570273 0.30119537 0.64593924 0.78732426]
 [0.02494332 0.58761679 0.83720853 0.3402494  0.54457607 0.78160655
  0.70851357 0.27922647 0.17528239 0.43633734]
 [0.83161229 0.39399907 0.3141351  0.83024837 0.94686456 0.55479214
  0.4616523  0.04120876 0.19513952 0.98982075]
 [0.50005648 0.08022074 0.15513689 0.3327177  0.22298382 0.41921595
  0.09863966 0.98323518 0.35890979 0.70453369]
 [0.93573362 0.24420001 0.09071685 0.09084727 0.90333408 0.05339215
  0.65335262 0.86943383 0.83845654 0.34465104]
 [0.39104337 0.63173171 0.9611393  0.64767603 0.42968324 0.3267296
  0.87878536 0

In [ ]:
# Create a zero array of size 10 and replace 5th element with 1.

arr = np.zeros(10)
print(arr)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1,2,0,0,4,0])
print(arr)
print()
arr_rev = np.flip(arr)
print("Reversed: ")
print(arr_rev)

[1 2 0 0 4 0]

Reversed: 
[0 4 0 0 2 1]


In [ ]:
# Create a 2d array with 1 on border and 0 inside.

def one_border(i,j):
  m = i.shape[0]
  n = i.shape[1]
  return (i == 0) | (i == m - 1) | (j == 0) | (j == n - 1)

shape = (12,20)

arr = np.fromfunction(one_border, shape, dtype=int).astype(int)
print(arr)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [ ]:
# Create a 8X8 matrix and fill it with a checkerboard pattern.
def checkerboard(i,j):
  return (i + j) % 2

shape = (8,8)
board = np.fromfunction(checkerboard, shape)
print(board)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Problem - 3: Array Operations:

In [ ]:
# define arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

In [ ]:
# Add
print("x + y")
print(x + y)
print()
print("v + w")
print(v + w)

x + y
[[ 6  8]
 [10 13]]

v + w
[20 22]


In [ ]:
# Subtract
print("x - y")
print(x - y)
print()
print("v - w")
print(v - w)

x - y
[[-4 -4]
 [-4 -3]]

v - w
[-2 -2]


In [ ]:
# Scalar Multiplication
print("4 * x")
print(4 * x)
print()
print("2 * y")
print(2 * y)
print()
print("14 * v")
print(14 * v)
print()
print("-2 * w")
print(-2 * w)
print()

4 * x
[[ 4  8]
 [12 20]]

2 * y
[[10 12]
 [14 16]]

14 * v
[126 140]

-2 * w
[-22 -24]



In [ ]:
# Dot products
print("v.w")
print(v.dot(w))
print()

print("x.v")
print(x @ v)
print()

print("x.y")
print(np.dot(x,y))

v.w
219

x.v
[29 77]

x.y
[[19 22]
 [50 58]]


In [ ]:
# Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
print("x")
print(x)
print("y")
print(y)
print("concatenated:")
print(np.vstack((x,y)))
print()
print("v")
print(v)
print("w")
print(w)
print("concatenated:")
print(np.concatenate((v,w)))

x
[[1 2]
 [3 5]]
y
[[5 6]
 [7 8]]
concatenated:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

v
[ 9 10]
w
[11 12]
concatenated:
[ 9 10 11 12]


In [ ]:
# Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

print(np.concatenate((x,v)))

# Explanation:
# Throws TypeError because the dimension of x and y is different
# 'x' is 2d while 'v' is 1d

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## Problem - 4: Matrix Operations:

In [ ]:
# Arrays:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

In [ ]:
# Prove A.A^(−1) = I
print("A")
print(A)
print()

A_inv = np.linalg.inv(A)
print("A^(-1)")
print(A_inv)
print()

A_A_inv = (A @ A_inv)
print("A.A^(−1)")
print(A_A_inv)
print()

I = np.eye(A.shape[0])
print("I")
print(I)
print()

print("Equal" if np.allclose(A_A_inv, I) else "Not Equal")

A
[[3 4]
 [7 8]]

A^(-1)
[[-2.    1.  ]
 [ 1.75 -0.75]]

A.A^(−1)
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

I
[[1. 0.]
 [0. 1.]]

Equal


In [ ]:
# Prove AB = ̸= BA.
print("AB")
print(A @ B)
print()

print("BA")
print(B @ A)
print()

print("Equal" if np.array_equal(B @ A, A @ B) else "Not Equal")

AB
[[23 13]
 [51 29]]

BA
[[36 44]
 [13 16]]

Not Equal


In [ ]:
# Prove (AB)^T = B^T.A^T
AB = A @ B
AB_t = np.linalg.matrix_transpose(AB)
B_t = np.linalg.matrix_transpose(B)
A_t = np.linalg.matrix_transpose(A)

B_t_A_t = B_t @ A_t

print("(AB)^T")
print(AB_t)
print()

print("B^T.A^T")
print(B_t_A_t)
print()

print("Equal" if np.array_equal(AB_t, B_t_A_t) else "Not Equal")

(AB)^T
[[23 51]
 [13 29]]

B^T.A^T
[[23 51]
 [13 29]]

Equal


In [ ]:
# Solver system of Linear equation using Inverse Methods

A = np.array([[2,-3,1], [1, -1, 2], [3,1,-1]])
B = np.array([[-1],[-3],[9]])

X = np.linalg.inv(A) @ B
x,y,z = X

print(f"x={x}, y={y}, z={z}")

x=[2.], y=[1.], z=[-2.]


# **10.2 Experiment: How Fast is Numpy?**

In [7]:
# Element-wise addition comparison
x = range(1_000_000)
y = range(1_000_000,0,-1)

start = time.time()
result = [x + y for x, y in zip(x,y)]
end = time.time()

print(f"Python list: {end - start}s")

x_np = np.arange(1_000_000)
y_np = np.arange(1_000_000,0,-1)
start_np = time.time()
result_np = x_np + y_np
end_np = time.time()
print(f"NP list: {end_np - start_np}s")

Python list: 0.11062359809875488s
NP list: 0.002206087112426758s


In [8]:
# ELement-wise multiplication
x = range(1_000_000)
y = range(1_000_000,0,-1)

start = time.time()
dot_product = [x * y for x, y in zip(x,y)]
end = time.time()

print(f"Python list: {end - start}s")

x_np = np.arange(1_000_000)
y_np = np.arange(1_000_000,0,-1)
start_np = time.time()
result_np = x_np * y_np
end_np = time.time()
print(f"NP list: {end_np - start_np}s")

Python list: 0.11015629768371582s
NP list: 0.002193927764892578s


In [9]:
# Dot Product
x = range(1_000_000)
y = range(1_000_000,0,-1)

start = time.time()
dot_product = sum(x * y for x, y in zip(x,y))
end = time.time()

print(f"Python list: {end - start}s, dot product = {dot_product}")

x_np = np.arange(1_000_000)
y_np = np.arange(1_000_000,0,-1)
start_np = time.time()
dot_product_np = np.dot(x_np, y_np)
end_np = time.time()
print(f"NP list: {end_np - start_np}s, dot product = {dot_product_np}")

Python list: 0.13077163696289062s, dot product = 166666666666500000
NP list: 0.0016887187957763672s, dot product = 166666666666500000


In [13]:
# Matrix multiplication
size = 500  #size reduced to 500 for quicker execution

A = [[x for x in range(size)] for _ in range(size)]
B = [[x for x in range(size)] for _ in range(size)]
C = [[0]*size for _ in range(size)]

start = time.time()

for i in range(size):
    for j in range(size):
        C[i][j] = sum(A[i][k] * B[k][j] for k in range(size))

end = time.time()

print(f"Python list: {end - start}s")

A_np = np.tile(np.arange(size), (size, 1))
B_np = np.tile(np.arange(size), (size, 1))

start_np = time.time()

C_np = np.dot(A_np, B_np)

end_np = time.time()

print(f"NP list: {end_np - start_np}s")

Python list: 22.671977043151855s
NP list: 0.1620311737060547s
